import express from"express";import{randomUUID}from"node:crypto";import{courses}from"./catalog.mjs";import{cookieValue,hashPassword,signSession,verifyPassword,verifySession}from"./auth.mjs";import{readStore,updateStore}from"./store.mjs";
const router=express.Router();router.use(express.json({limit:"100kb"}));const safeUser=u=>({id:u.id,name:u.name,email:u.email,createdAt:u.createdAt});
async function currentUser(req){const token=cookieValue(req.headers.cookie,"alkule_session"),session=token&&verifySession(token);if(!session)return null;const data=await readStore();return data.users.find(u=>u.id===session.userId)||null}
router.get("/health",(_req,res)=>res.json({ok:true,service:"alkule-api",time:new Date().toISOString()}));
router.get("/courses",(req,res)=>{const q=String(req.query.q||"").toLowerCase(),level=String(req.query.level||""),format=String(req.query.format||"");res.json(courses.filter(c=>(!q||`${c.title} ${c.description}`.toLowerCase().includes(q))&&(!level||level==="All"||c.level===level)&&(!format||format==="All"||c.format===format)))});
router.post("/auth/signup",async(req,res)=>{const name=String(req.body.name||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(name.length<2||!email.includes("@")||password.length<8)return res.status(400).json({error:"Enter a name, valid email, and password of at least 8 characters."});const user=await updateStore(data=>{if(data.users.some(u=>u.email===email))return null;const created={id:randomUUID(),name,email,passwordHash:hashPassword(password),createdAt:new Date().toISOString()};data.users.push(created);return created});if(!user)return res.status(409).json({error:"An account with this email already exists."});const token=signSession({userId:user.id,expiresAt:Date.now()+604800000});res.setHeader("Set-Cookie",`alkule_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${process.env.NODE_ENV==="production"?"; Secure":""}`);res.status(201).json({user:safeUser(user)})});
router.post("/auth/login",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),data=await readStore(),user=data.users.find(u=>u.email===email);if(!user||!verifyPassword(password,user.passwordHash))return res.status(401).json({error:"Email or password is incorrect."});const token=signSession({userId:user.id,expiresAt:Date.now()+604800000});res.setHeader("Set-Cookie",`alkule_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${process.env.NODE_ENV==="production"?"; Secure":""}`);res.json({user:safeUser(user)})});
router.post("/auth/logout",(_req,res)=>{res.setHeader("Set-Cookie","alkule_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0");res.status(204).end()});
router.get("/auth/me",async(req,res)=>{const user=await currentUser(req);if(!user)return res.status(401).json({error:"Not signed in."});res.json({user:safeUser(user)})});
router.get("/dashboard",async(req,res)=>{const user=await currentUser(req);if(!user)return res.status(401).json({error:"Sign in to load your dashboard."});const data=await readStore(),progress=data.progress.find(p=>p.userId===user.id)||{score:0,attempts:0,correct:0,streak:0,updatedAt:null};res.json({user:safeUser(user),progress,reviewsDue:Math.min(3,Math.max(0,progress.attempts-progress.correct)),nextCourse:courses[0]})});
router.put("/progress/typing",async(req,res)=>{const user=await currentUser(req);if(!user)return res.status(401).json({error:"Sign in to save progress."});const clean={score:Math.max(0,Number(req.body.score)||0),attempts:Math.max(0,Number(req.body.attempts)||0),correct:Math.max(0,Number(req.body.correct)||0),streak:Math.max(0,Number(req.body.streak)||0),updatedAt:new Date().toISOString()};await updateStore(data=>{const index=data.progress.findIndex(p=>p.userId===user.id),row={userId:user.id,...clean};if(index>=0)data.progress[index]=row;else data.progress.push(row)});res.json({progress:clean})});
router.post("/newsletter",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:"Enter a valid email address."});await updateStore(data=>{if(!data.newsletters.some(x=>x.email===email))data.newsletters.push({email,createdAt:new Date().toISOString()})});res.status(201).json({message:"You are on the Alkule update list."})});
router.use((error,_req,res,_next)=>{console.error(error);res.status(500).json({error:"The server could not complete this request."})});export default router;
