import Image from "next/image";
import Link from "next/link";

const columns = {
  Learn: [["Free Typing","/learn/typing"],["Beginner","/courses?level=Beginner"],["Intermediate","/courses?level=Intermediate"],["Advanced","/courses?level=Advanced"],["Self-paced courses","/courses?format=Self-paced"],["Live courses","/courses?format=Live"],["Certificates","/dashboard"]],
  Explore: [["Art & Culture","/art-culture"],["Podcast","/podcast"],["Literature","/literature"],["History","/history"],["Library","/library"],["Community","/community"]],
  Teach: [["Become an instructor","/teach"],["Instructor requirements","/teach#requirements"],["Create a course","/teach#steps"],["Teach live","/teach#live"],["Instructor support","/help"]],
  Support: [["Help Center","/help"],["Install an ADLaM font","/help#font"],["Install an ADLaM keyboard","/help#keyboard"],["Low-data mode","/accessibility"],["Captions and transcripts","/accessibility"],["Accessibility","/accessibility"],["Report a problem","/help#report"]],
  Legal: [["Terms","/legal#terms"],["Privacy","/legal#privacy"],["Cookies","/legal#cookies"],["Refund policy","/legal#refunds"],["Community guidelines","/community#guidelines"],["Copyright","/legal#copyright"]],
} as const;
const social = [["Facebook","https://www.facebook.com/profile.php?id=61592028694728"],["Instagram","https://www.instagram.com/alkule_"],["YouTube","https://www.youtube.com/@Alkule"],["LinkedIn","https://www.linkedin.com/company/alkule/"]] as const;

export default function Footer(){return <footer className="bg-indigo-deep text-white"><div className="container-page py-14"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-6"><div><Image src="/assets/Logo.png" alt="Alkule" width={165} height={50} className="h-auto w-40"/><p className="mt-4 text-sm leading-6 text-white/70">ADLaM-first learning and cultural resources for Fulani people and interested learners worldwide.</p><div className="mt-4 flex flex-wrap gap-3">{social.map(([label,href])=><a key={href} href={href} target="_blank" rel="noopener noreferrer" className="min-h-11 content-center text-sm underline" aria-label={`${label} (opens in a new tab)`}>{label}</a>)}</div></div>{Object.entries(columns).map(([title,links])=><section key={title}><h2 className="font-bold text-alkule-cyan">{title}</h2><ul className="mt-3 space-y-2">{links.map(([label,href])=><li key={label}><Link href={href} className="text-sm text-white/75 hover:text-white">{label}</Link></li>)}</ul></section>)}</div><p className="mt-12 border-t border-white/15 pt-6 text-xs text-white/60">© {new Date().getFullYear()} Alkule. Sample frontend experience; account, purchase, and certificate services are not yet connected.</p></div></footer>}
