"use client";
import{useEffect,useMemo,useRef,useState}from"react";import{ADLAM_LETTERS,type AdlamLetter}from"@/data/adlam";import{applyAnswer,newRecord,type MasteryRecord}from"@/lib/srs";
const COUNT=6,STORAGE_KEY="alkule.typing.progress";function buildRound(seed:number){const target=ADLAM_LETTERS[seed%ADLAM_LETTERS.length],options:Array<AdlamLetter>=[];for(let i=0;options.length<COUNT;i++){const x=ADLAM_LETTERS[(seed+i*5)%ADLAM_LETTERS.length];if(!options.some(o=>o.index===x.index))options.push(x)}return{target,options}}
export default function TypingGame(){const[seed,setSeed]=useState(0),[score,setScore]=useState(0),[attempts,setAttempts]=useState(0),[correct,setCorrect]=useState(0),[streak,setStreak]=useState(0),[feedback,setFeedback]=useState(''),[locked,setLocked]=useState(false),[mastery,setMastery]=useState<Record<number,MasteryRecord>>({}),[showKeyboard,setShowKeyboard]=useState(true),[restored,setRestored]=useState(false);const timer=useRef<number>(),round=useMemo(()=>buildRound(seed),[seed]),accuracy=attempts?Math.round(correct/attempts*100):0,weakest=useMemo(()=>Object.values(mastery).filter(x=>x.wrong).sort((a,b)=>a.level-b.level).slice(0,3),[mastery]);
useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(saved){setScore(saved.score||0);setAttempts(saved.attempts||0);setCorrect(saved.correct||0);setStreak(saved.streak||0);setSeed(saved.seed||0)}}finally{setRestored(true)}},[]);
useEffect(()=>{if(!restored)return;const progress={score,attempts,correct,streak,seed};localStorage.setItem(STORAGE_KEY,JSON.stringify(progress));if(attempts>0)fetch('/api/progress/typing',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(progress)}).catch(()=>undefined)},[score,attempts,correct,streak,seed,restored]);
function answer(letter:AdlamLetter){if(locked)return;setLocked(true);const ok=letter.index===round.target.index;setAttempts(a=>a+1);setCorrect(c=>c+(ok?1:0));setScore(s=>s+(ok?10:0));setStreak(s=>ok?s+1:0);setFeedback(ok?`Correct: ${round.target.name}`:`Try again next round. This is ${round.target.name}.`);setMastery(m=>{const rec=m[round.target.index]??newRecord(round.target.index);return{...m,[round.target.index]:applyAnswer(rec,ok)}});timer.current=window.setTimeout(()=>{setSeed(s=>s+1);setLocked(false);setFeedback('')},700)}
useEffect(()=>()=>window.clearTimeout(timer.current),[]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key>='1'&&e.key<='6')answer(round.options[Number(e.key)-1])};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
function reset(){window.clearTimeout(timer.current);setSeed(0);setScore(0);setAttempts(0);setCorrect(0);setStreak(0);setMastery({});setFeedback('');setLocked(false);localStorage.removeItem(STORAGE_KEY)}
return <div className="container-page grid gap-6 py-8 lg:grid-cols-[16rem_1fr]"><aside className="card h-fit p-5"><h2 className="font-bold">Session stats</h2><dl className="mt-4 grid grid-cols-2 gap-3 text-center"><div className="rounded-lg bg-paper p-3"><dt className="text-xs text-muted">Score</dt><dd className="text-2xl font-bold">{score}</dd></div><div className="rounded-lg bg-paper p-3"><dt className="text-xs text-muted">Streak</dt><dd className="text-2xl font-bold">{streak}</dd></div><div className="col-span-2 rounded-lg bg-paper p-3"><dt className="text-xs text-muted">Accuracy</dt><dd className="text-2xl font-bold">{accuracy}%</dd></div></dl><h3 className="mt-6 font-bold">Practice mode</h3><p className="mt-2 rounded-lg bg-cyan-100 p-3 text-sm font-bold">Letter recognition</p><button onClick={()=>setShowKeyboard(v=>!v)} className="mt-3 min-h-11 text-sm font-bold text-indigo-brand" aria-expanded={showKeyboard}>{showKeyboard?'Hide':'Show'} keyboard choices</button><p className="mt-8 rounded-xl bg-indigo-deep p-4 text-sm text-white">Progress is stored on this device. Signed-in learners also save it to their Alkule account.</p>{weakest.length>0&&<div className="mt-5"><h3 className="text-sm font-bold">Review summary</h3><p className="adlam mt-2 text-2xl">{weakest.map(r=>ADLAM_LETTERS[r.letterIndex].capital).join(' ')}</p></div>}</aside><section className="card p-6 text-center sm:p-10" aria-labelledby="lab-heading"><p className="eyebrow">Target character</p><h2 id="lab-heading" className="mt-2 text-2xl font-bold">Choose the ADLaM letter for <bdi>{round.target.name}</bdi></h2><p className="mt-2 text-muted">Use a choice button or number keys 1–6.</p><div className="mx-auto mt-8 grid h-52 max-w-xs place-items-center rounded-3xl border border-border bg-paper"><span className="text-lg font-bold">{round.target.name} <span className="text-muted">({round.target.roman})</span></span></div>{showKeyboard&&<div className="mx-auto mt-8 grid max-w-2xl grid-cols-3 gap-3 sm:grid-cols-6">{round.options.map((letter,i)=><button key={letter.index} disabled={locked} onClick={()=>answer(letter)} className="adlam min-h-20 rounded-xl border border-border bg-white text-4xl hover:border-alkule-teal disabled:cursor-wait disabled:opacity-60" aria-label={`${i+1}: ${letter.name}`}><span>{letter.capital}</span><span className="block font-body text-xs text-muted">{i+1}</span></button>)}</div>}<p className="mt-6 min-h-7 font-bold" aria-live="polite">{feedback}</p><button onClick={reset} className="mt-3 min-h-11 text-sm font-bold underline">Start session over</button></section></div>}
